# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asmr_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'asmr_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61smr_service.proto\x12\x04\x61smr\"w\n\x14GenerateStoryRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x17\n\nmax_tokens\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0btemperature\x18\x03 \x01(\x02H\x01\x88\x01\x01\x42\r\n\x0b_max_tokensB\x0e\n\x0c_temperature\"I\n\x15GenerateStoryResponse\x12\r\n\x05story\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xd5\x01\n\x14GenerateAudioRequest\x12\x12\n\nstory_file\x18\x01 \x01(\t\x12\x30\n\x0evoice_settings\x18\x02 \x01(\x0b\x32\x13.asmr.VoiceSettingsH\x00\x88\x01\x01\x12!\n\x14use_background_music\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12\x18\n\x0bvoice_index\x18\x04 \x01(\x05H\x02\x88\x01\x01\x42\x11\n\x0f_voice_settingsB\x17\n\x15_use_background_musicB\x0e\n\x0c_voice_index\"i\n\rVoiceSettings\x12\x11\n\x04rate\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06volume\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x12\n\x05pitch\x18\x03 \x01(\x02H\x02\x88\x01\x01\x42\x07\n\x05_rateB\t\n\x07_volumeB\x08\n\x06_pitch\"@\n\x15GenerateAudioResponse\x12\x17\n\x0f\x61udio_file_path\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\xbf\x01\n\x1dGenerateStoryAndAudioResponse\x12\r\n\x05story\x18\x01 \x01(\t\x12\x17\n\x0fstory_file_path\x18\x02 \x01(\t\x12\x17\n\x0f\x61udio_file_path\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x35\n\x13used_voice_settings\x18\x05 \x01(\x0b\x32\x13.asmr.VoiceSettingsH\x00\x88\x01\x01\x42\x16\n\x14_used_voice_settings2\x81\x02\n\x0b\x41smrService\x12J\n\rGenerateStory\x12\x1a.asmr.GenerateStoryRequest\x1a\x1b.asmr.GenerateStoryResponse\"\x00\x12J\n\rGenerateAudio\x12\x1a.asmr.GenerateAudioRequest\x1a\x1b.asmr.GenerateAudioResponse\"\x00\x12Z\n\x15GenerateStoryAndAudio\x12\x1a.asmr.GenerateStoryRequest\x1a#.asmr.GenerateStoryAndAudioResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asmr_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATESTORYREQUEST']._serialized_start=28
  _globals['_GENERATESTORYREQUEST']._serialized_end=147
  _globals['_GENERATESTORYRESPONSE']._serialized_start=149
  _globals['_GENERATESTORYRESPONSE']._serialized_end=222
  _globals['_GENERATEAUDIOREQUEST']._serialized_start=225
  _globals['_GENERATEAUDIOREQUEST']._serialized_end=438
  _globals['_VOICESETTINGS']._serialized_start=440
  _globals['_VOICESETTINGS']._serialized_end=545
  _globals['_GENERATEAUDIORESPONSE']._serialized_start=547
  _globals['_GENERATEAUDIORESPONSE']._serialized_end=611
  _globals['_GENERATESTORYANDAUDIORESPONSE']._serialized_start=614
  _globals['_GENERATESTORYANDAUDIORESPONSE']._serialized_end=805
  _globals['_ASMRSERVICE']._serialized_start=808
  _globals['_ASMRSERVICE']._serialized_end=1065
# @@protoc_insertion_point(module_scope)
