# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import asmr_service_pb2 as asmr__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in asmr_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AsmrServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStory = channel.unary_unary(
                '/asmr.AsmrService/GenerateStory',
                request_serializer=asmr__service__pb2.GenerateStoryRequest.SerializeToString,
                response_deserializer=asmr__service__pb2.GenerateStoryResponse.FromString,
                _registered_method=True)
        self.GenerateAudio = channel.unary_unary(
                '/asmr.AsmrService/GenerateAudio',
                request_serializer=asmr__service__pb2.GenerateAudioRequest.SerializeToString,
                response_deserializer=asmr__service__pb2.GenerateAudioResponse.FromString,
                _registered_method=True)
        self.GenerateStoryAndAudio = channel.unary_unary(
                '/asmr.AsmrService/GenerateStoryAndAudio',
                request_serializer=asmr__service__pb2.GenerateStoryRequest.SerializeToString,
                response_deserializer=asmr__service__pb2.GenerateStoryAndAudioResponse.FromString,
                _registered_method=True)


class AsmrServiceServicer(object):
    """Service definition
    """

    def GenerateStory(self, request, context):
        """Generate a conspiracy story text based on a topic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAudio(self, request, context):
        """Convert a story to audio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStoryAndAudio(self, request, context):
        """Generate both story and audio in one call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsmrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateStory': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStory,
                    request_deserializer=asmr__service__pb2.GenerateStoryRequest.FromString,
                    response_serializer=asmr__service__pb2.GenerateStoryResponse.SerializeToString,
            ),
            'GenerateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAudio,
                    request_deserializer=asmr__service__pb2.GenerateAudioRequest.FromString,
                    response_serializer=asmr__service__pb2.GenerateAudioResponse.SerializeToString,
            ),
            'GenerateStoryAndAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStoryAndAudio,
                    request_deserializer=asmr__service__pb2.GenerateStoryRequest.FromString,
                    response_serializer=asmr__service__pb2.GenerateStoryAndAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asmr.AsmrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asmr.AsmrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsmrService(object):
    """Service definition
    """

    @staticmethod
    def GenerateStory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asmr.AsmrService/GenerateStory',
            asmr__service__pb2.GenerateStoryRequest.SerializeToString,
            asmr__service__pb2.GenerateStoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asmr.AsmrService/GenerateAudio',
            asmr__service__pb2.GenerateAudioRequest.SerializeToString,
            asmr__service__pb2.GenerateAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStoryAndAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asmr.AsmrService/GenerateStoryAndAudio',
            asmr__service__pb2.GenerateStoryRequest.SerializeToString,
            asmr__service__pb2.GenerateStoryAndAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
